WITH CTE AS (
    SELECT PARENT_ID AS PID,
        COUNT(PARENT_ID) AS CNT
    FROM ECOLI_DATA
    GROUP BY PARENT_ID
)

SELECT ID, COALESCE(CNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA AS E
LEFT JOIN CTE AS C
    ON E.ID = C.PID;