WITH a as (select FOOD_TYPE, MAX(FAVORITES)as MX
FROM REST_INFO
GROUP BY 1)

SELECT r.FOOD_TYPE, r.REST_ID, r.REST_NAME, r.FAVORITES
FROM REST_INFO as r, a
WHERE r.FOOD_TYPE = a.FOOD_TYPE
AND r.FAVORITES= a.MX
ORDER BY 1 desc