SELECT r.REST_ID
, r.REST_NAME
, r.FOOD_TYPE
, r.FAVORITES
, r.ADDRESS
, ROUND(AVG(y.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO AS r

LEFT JOIN REST_REVIEW AS y ON r.REST_ID = y.REST_ID

WHERE ADDRESS LIKE '서울%' AND REVIEW_SCORE IS NOT NULL

GROUP BY REST_ID
ORDER BY SCORE DESC, FAVORITES DESC