SELECT YEAR(y.SALES_DATE) AS YEAR
, MONTH(y.SALES_DATE) AS MONTH
, r.GENDER
, COUNT(DISTINCT r.USER_ID) AS USERS
FROM USER_INFO AS r

LEFT JOIN ONLINE_SALE AS y ON r.USER_ID = y.USER_ID

WHERE y.SALES_DATE IS NOT NULL AND r.GENDER IS NOT NULL

GROUP BY 1, 2, 3
ORDER BY 1, 2, 3