SELECT 
    T.ID,   
    FN.FISH_NAME,
    T.LENGTH
FROM (
    SELECT 
        FI.ID,
        FI.FISH_TYPE,
        FI.LENGTH,
        RANK() OVER (PARTITION BY FI.FISH_TYPE ORDER BY LENGTH DESC) AS RNK
    FROM FISH_INFO FI
    WHERE 1 = 1 
    AND FI.LENGTH IS NOT NULL 
) T
INNER JOIN FISH_NAME_INFO FN 
USING (FISH_TYPE)
WHERE T.RNK = 1
ORDER BY ID ASC